/**
 * MediaAsset ID generator (STORAGE-1R / D-067).
 *
 * Prisma's MediaAsset.id is generated by `@default(cuid())` (see
 * prisma/schema.prisma: "IDs: cuid() generated"), and Prisma 7 does not export
 * a public cuid helper. We use the `cuid` package — a 25-character, lowercase,
 * alphanumeric, time-prefixed ID that matches Prisma's `cuid()` output format.
 *
 * Declared as a direct dependency in package.json (`cuid@^3.0.0`).
 *
 * `isMediaAssetId` validates the canonical cuid v1 / v2 shape so any
 * preallocated upload ID passes every existing MediaAsset ID validator in the
 * project.
 */

import cuid from 'cuid';

/**
 * cuid v1 / v2 canonical shape: 25 chars, starts with `c`, lowercase
 * alphanumeric (no `0`, `O`, `I`, `L` after the leading letter).
 */
const CUID_PATTERN = /^c[a-z0-9]{24}$/;

export function newMediaAssetId(): string {
  return cuid();
}

export function isMediaAssetId(value: string): boolean {
  return CUID_PATTERN.test(value);
}
